class Localization {
  static const Map<String, Map<String, String>> strings = {
    'tr': {
      'game_over': 'OYUN BİTTİ',
      'score': 'Skorunuz:',
      'gold_earned': '+{val} Altın',
      'retry': 'YENİDEN DENE',
      'main_menu': 'ANA MENÜYE ÇIK',
      'shop': 'MARKET',
      'classic_mode': 'KLASİK MOD',
      'time_attack': 'HIZ MODU',
      'sparring': 'SPARRING',
      'settings': 'AYARLAR',
      'language': 'Dil Seçimi',
      'how_to_play': 'NASIL OYNANIR?',
      'classic_desc': 'Bombalara\ndokunma!\n3 Canın var.',
      'time_desc': 'Bombaları kesme,\neksi puan verir.\nSüre: 60s',
      'sparring_desc': 'Yiyecekleri keserek\nenerjini dolu tut!',
      'hud_score': 'SKOR: {val}',
      'hud_time': 'SÜRE: {val}',
      'equipped': 'KUŞANILDI',
      'equip': 'KUŞAN',
      'buy': 'SATIN AL',
      'trails_title': 'İZLER (TRAILS)',
      'bg_title': 'ARKA PLANLAR',
      'Beyaz': 'Beyaz',
      'Neon Yeşil': 'Neon Yeşil',
      'Ateş Rengi': 'Ateş Rengi',
      'Klasik Ahşap': 'Vip Klasik Ahşap',
      'Neon Mutfak': 'Siber Neon Mutfak',
      'Retro Fayans': '80\'ler Retro Fayans',
      'Zıtlık Arenası': 'Zıtlık Arenası',
      'hits': '{val} VURUŞ',
      'combo': '{val} KOMBO',
    },
    'en': {
      'game_over': 'GAME OVER',
      'score': 'Your Score:',
      'gold_earned': '+{val} Gold',
      'retry': 'RETRY',
      'main_menu': 'MAIN MENU',
      'shop': 'SHOP',
      'classic_mode': 'CLASSIC MODE',
      'time_attack': 'TIME ATTACK',
      'sparring': 'SPARRING',
      'settings': 'SETTINGS',
      'language': 'Language Selection',
      'how_to_play': 'HOW TO PLAY',
      'classic_desc': 'Do not touch\nthe bombs!\nYou have 3 lives.',
      'time_desc': 'Bombs give\nnegative points.\nTime: 60s.',
      'sparring_desc': 'Keep your energy\nfull by slashing!',
      'hud_score': 'SCORE: {val}',
      'hud_time': 'TIME: {val}',
      'equipped': 'EQUIPPED',
      'equip': 'EQUIP',
      'buy': 'BUY',
      'trails_title': 'TRAILS',
      'bg_title': 'BACKGROUNDS',
      'Beyaz': 'White',
      'Neon Yeşil': 'Neon Green',
      'Ateş Rengi': 'Fire Color',
      'Klasik Ahşap': 'Premium Wood',
      'Neon Mutfak': 'Neon Cyber Kitchen',
      'Retro Fayans': '80\'s Retro Tiles',
      'Zıtlık Arenası': 'Clash Arena',
      'hits': '{val} HITS',
      'combo': '{val} COMBO',
    },
    'es': {
      'game_over': 'FIN DEL JUEGO',
      'score': 'Tu Puntuación:',
      'gold_earned': '+{val} Oro',
      'retry': 'REINTENTAR',
      'main_menu': 'MENÚ PRINCIPAL',
      'shop': 'TIENDA',
      'classic_mode': 'MODO CLÁSICO',
      'time_attack': 'CONTRARRELOJ',
      'sparring': 'ENTRENAMIENTO',
      'settings': 'AJUSTES',
      'language': 'Idioma',
      'how_to_play': 'CÓMO JUGAR',
      'classic_desc': '¡No toques las\nbombas!\nTienes 3 vidas.',
      'time_desc': 'Las bombas restan\npuntos.\nTiempo: 60s',
      'sparring_desc': '¡Mantén tu energía\ncortando comida!',
      'hud_score': 'PUNTOS: {val}',
      'hud_time': 'TIEMPO: {val}',
      'equipped': 'EQUIPADO',
      'equip': 'EQUIPAR',
      'buy': 'COMPRAR',
      'trails_title': 'RASTROS',
      'bg_title': 'FONDOS',
      'Beyaz': 'Blanco',
      'Neon Yeşil': 'Verde Neón',
      'Ateş Rengi': 'Color Fuego',
      'Klasik Ahşap': 'Madera Clásica',
      'Neon Mutfak': 'Cocina de Neón',
      'Retro Fayans': 'Azulejos Retro',
      'Zıtlık Arenası': 'Arena de Choque',
      'hits': '{val} GOLPES',
      'combo': '{val} COMBO',
    },
    'fr': {
      'game_over': 'FIN DE PARTIE',
      'score': 'Votre Score:',
      'gold_earned': '+{val} Or',
      'retry': 'RÉESSAYER',
      'main_menu': 'MENU PRINCIPAL',
      'shop': 'BOUTIQUE',
      'classic_mode': 'CLASSIQUE',
      'time_attack': 'CONTRE LA MONTRE',
      'sparring': 'ENTRAÎNEMENT',
      'settings': 'PARAMÈTRES',
      'language': 'Langue',
      'how_to_play': 'COMMENT JOUER',
      'classic_desc': 'Ne touchez pas\npas aux bombes!\n3 vies.',
      'time_desc': 'Les bombes\nenlèvent des points.\nTemps: 60s',
      'sparring_desc': 'Gardez de\nl\'énergie!',
      'hud_score': 'SCORE: {val}',
      'hud_time': 'TEMPS: {val}',
      'equipped': 'ÉQUIPÉ',
      'equip': 'ÉQUIPER',
      'buy': 'ACHETER',
      'trails_title': 'TRAÎNÉES',
      'bg_title': 'FONDS',
      'Beyaz': 'Blanc',
      'Neon Yeşil': 'Vert Néon',
      'Ateş Rengi': 'Couleur Feu',
      'Klasik Ahşap': 'Bois Classique',
      'Neon Mutfak': 'Cuisine Néon',
      'Retro Fayans': 'Tuiles Rétro',
      'Zıtlık Arenası': 'Arène de Choc',
      'hits': '{val} COUPS',
      'combo': '{val} COMBO',
    },
    'de': {
      'game_over': 'SPIEL VORBEI',
      'score': 'Dein Ergebnis:',
      'gold_earned': '+{val} Gold',
      'retry': 'WIEDERHOLEN',
      'main_menu': 'HAUPTMENÜ',
      'shop': 'SHOP',
      'classic_mode': 'KLASSISCH',
      'time_attack': 'ZEITANGRIFF',
      'sparring': 'TRAINING',
      'settings': 'EINSTELLUNGEN',
      'language': 'Sprache',
      'how_to_play': 'SPIELANLEITUNG',
      'classic_desc': 'Berühre keine\nBomben!\nDu hast 3 Leben.',
      'time_desc': 'Bomben bringen\nMinuspunkte.\nZeit: 60s',
      'sparring_desc': 'Halte deine\nEnergie hoch!',
      'hud_score': 'PUNKTE: {val}',
      'hud_time': 'ZEIT: {val}',
      'equipped': 'AUSGERÜSTET',
      'equip': 'AUSRÜSTEN',
      'buy': 'KAUFEN',
      'trails_title': 'SPUREN',
      'bg_title': 'HINTERGRÜNDE',
      'Beyaz': 'Weiß',
      'Neon Yeşil': 'Neongrün',
      'Ateş Rengi': 'Feuerfarbe',
      'Klasik Ahşap': 'Klassisches Holz',
      'Neon Mutfak': 'Neon Küche',
      'Retro Fayans': 'Retro-Fliesen',
      'Zıtlık Arenası': 'Konflikt-Arena',
      'hits': '{val} TREFFER',
      'combo': '{val} KOMBO',
    }
  };

  static String get(String langCode, String key, {Map<String, String>? params}) {
    final langMap = strings[langCode] ?? strings['en']!;
    String result = langMap[key] ?? key;
    
    if (params != null) {
      params.forEach((k, v) {
        result = result.replaceAll('{$k}', v);
      });
    }
    return result;
  }
}
